import { useState } from "react";
import type { MouseEventHandler } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import { LazyImage } from "../../components/RandomFox";

const inter = Inter({ subsets: ["latin"] });

//generar a random function  1 a 123
const random = () => Math.floor(Math.random() * 123) + 1
type ImageItem = {id: string, url: string}

// generate simple unique id 
const generateId = () => Math.random().toString(36).substr(2, 9);


export default function Home() {
  const [images, setImages] = useState<Array<ImageItem>>([])

  const addNewFox: MouseEventHandler<HTMLButtonElement> = (event) => { // modo profesional de typescript para eventos de boton
    const newImageitem = {
      id: generateId(),
      url: `https://randomfox.ca/images/${random()}.jpg`
    }
    setImages([...images, newImageitem])
  }
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <h1 className="text-3xl font-bold underline">
        Hello, Platzi!
      </h1>
      <button onClick={addNewFox} >Add new fox</button>
      {images.map(({id, url}) => (
        <div key={id} className="p-4">
          <LazyImage 
            alt={'Fox'} 
            src={url} 
            title="Random Fox" 
            width={320} 
            height="auto"
            className="rounded bg-gray-300"
            onClick={() => console.log('hola')} 
          />
        </div>
      ))}
      </main>
    </>
  );
}
