import Head from "next/head";
import { Inter } from "next/font/google";
import { RandonFox } from "../../components/RandomFox";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const random = Math.floor(Math.random() * 123) + 1
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <h1 className="text-3xl font-bold underline">
        Hello, Platzi!
        
      </h1>
      <RandonFox alt={'Fox'} image={`https://randomfox.ca/images/${random}.jpg`}/>
      </main>
    </>
  );
}
